//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.03 at 12:10:04 AM UYT 
//


package com.tercevall.crsreport.input.entities;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CrsBody_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CrsBody_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ReportingFI" type="{urn:oecd:ties:crs:v1}CorrectableOrganisationParty_Type"/>
 *         &lt;element name="ReportingGroup" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Sponsor" type="{urn:oecd:ties:crs:v1}CorrectableOrganisationParty_Type" maxOccurs="0" minOccurs="0"/>
 *                   &lt;element name="Intermediary" type="{urn:oecd:ties:crs:v1}CorrectableOrganisationParty_Type" maxOccurs="0" minOccurs="0"/>
 *                   &lt;element name="AccountReport" type="{urn:oecd:ties:crs:v1}CorrectableAccountReport_Type" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="PoolReport" type="{urn:oecd:ties:fatca:v1}CorrectablePoolReport_Type" maxOccurs="0" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CrsBody_Type", namespace = "urn:oecd:ties:crs:v1", propOrder = {
    "reportingFI",
    "reportingGroup"
})
public class CrsBodyType {

    @XmlElement(name = "ReportingFI", required = true)
    protected CorrectableOrganisationPartyType reportingFI;
    @XmlElement(name = "ReportingGroup", required = true)
    protected List<CrsBodyType.ReportingGroup> reportingGroup;

    /**
     * Gets the value of the reportingFI property.
     * 
     * @return
     *     possible object is
     *     {@link CorrectableOrganisationPartyType }
     *     
     */
    public CorrectableOrganisationPartyType getReportingFI() {
        return reportingFI;
    }

    /**
     * Sets the value of the reportingFI property.
     * 
     * @param value
     *     allowed object is
     *     {@link CorrectableOrganisationPartyType }
     *     
     */
    public void setReportingFI(CorrectableOrganisationPartyType value) {
        this.reportingFI = value;
    }

    /**
     * Gets the value of the reportingGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reportingGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReportingGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CrsBodyType.ReportingGroup }
     * 
     * 
     */
    public List<CrsBodyType.ReportingGroup> getReportingGroup() {
        if (reportingGroup == null) {
            reportingGroup = new ArrayList<CrsBodyType.ReportingGroup>();
        }
        return this.reportingGroup;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Sponsor" type="{urn:oecd:ties:crs:v1}CorrectableOrganisationParty_Type" maxOccurs="0" minOccurs="0"/>
     *         &lt;element name="Intermediary" type="{urn:oecd:ties:crs:v1}CorrectableOrganisationParty_Type" maxOccurs="0" minOccurs="0"/>
     *         &lt;element name="AccountReport" type="{urn:oecd:ties:crs:v1}CorrectableAccountReport_Type" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="PoolReport" type="{urn:oecd:ties:fatca:v1}CorrectablePoolReport_Type" maxOccurs="0" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "accountReport"
    })
    public static class ReportingGroup {

        @XmlElement(name = "AccountReport", namespace = "urn:oecd:ties:crs:v1")
        protected List<CorrectableAccountReportType> accountReport;

        /**
         * Gets the value of the accountReport property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the accountReport property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAccountReport().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CorrectableAccountReportType }
         * 
         * 
         */
        public List<CorrectableAccountReportType> getAccountReport() {
            if (accountReport == null) {
                accountReport = new ArrayList<CorrectableAccountReportType>();
            }
            return this.accountReport;
        }

    }

}
